---
## ArcadeDB Credentials
:environment:
  :test:
    dbname: test
    user:  root
    pass: ***
  :development:
    dbname: devel
    user: root
    pass: ***
  :production:
    dbname: DeFi
    user: root
    pass: ***
:admin:
  :host: localhost
  :port: 2480
  :user: root
  :pass: *** 
:logger: stdout           # 'file' or 'stdout'
:namespace: Arcade

