---
## ArcadeDB Credentials
:pg:
 :host: localhost # 172.28.50.25 
 :port: 5432
:environment:
  :test:
    dbname: test
    user:  root
    pass: topo1focus
  :development:
    dbname: devel
    user: root
    pass: topo1focus
  :production:
    dbname: DeFi
    user: root
    pass: topo1focus
:admin:
  :host: localhost
  :port: 2480
  :user: root
  :pass: topo1focus 
:logger: stdout           # 'file' or 'stdout'
:namespace: Arcade

